// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YouApiKey',
    appId: '1:215253106893:web:7586b79177484a50606984',
    messagingSenderId: '215253106893',
    projectId: 'save-contact-1ec7e',
    authDomain: 'save-contact-1ec7e.firebaseapp.com',
    storageBucket: 'save-contact-1ec7e.appspot.com',
    measurementId: 'G-VEXR7SYJPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YouApiKey',
    appId: '1:215253106893:android:80f258d47ce5de88606984',
    messagingSenderId: '215253106893',
    projectId: 'save-contact-1ec7e',
    storageBucket: 'save-contact-1ec7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YouApiKey',
    appId: '1:215253106893:ios:574831a0cdd658d5606984',
    messagingSenderId: '215253106893',
    projectId: 'save-contact-1ec7e',
    storageBucket: 'save-contact-1ec7e.appspot.com',
    iosBundleId: 'com.example.saveContact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YouApiKey',
    appId: '1:215253106893:ios:0b4af84f03f86e09606984',
    messagingSenderId: '215253106893',
    projectId: 'save-contact-1ec7e',
    storageBucket: 'save-contact-1ec7e.appspot.com',
    iosBundleId: 'com.example.saveContact.RunnerTests',
  );
}
